### ISSUE TITLE
Strange behavior when enabling an already enabled switch

### ISSUE THREAD

**Issue by afru** [abpetkov/switchery#103]
If I try to call .enable() on a switch that is already enabled, I get some strange behavior. It seems like multiple handles are than bound to the switch, meaning that when I click on a switch it will click multiple times.  Don't know if this is an issue? If so, maybe it can be corrected by adding isDisabled() in the enable() method.

**Comment by phrix32** [comment]
Additionally if you disable an element which you enabled twice, you can switch the state of the switchery element again.

**Reproduce:**
On **http://abpetkov.github.io/switchery/** under **section "Disabled"** you have three examples of disabling / enabling a switchery element. Use the **third example** with an "Enable" and "Disable" button next to the switchery element. The element is disabled by default.

1. Enable the disabled switchery element by clicking on the "Enable" button:
Everything should work as expected

2. Click on the "Enable" button again:
You can't change the state of switchery element anymore by clicking on it

3. Click on the "Disable" button:
Now you can change the state of the switchery element again by clicking on it,
but the element is still greyed out like it is disabled
