### ISSUE TITLE
Don't work in iphone

### ISSUE THREAD

**Issue by cwtuan** [abpetkov/switchery#107]
In Chrome device simulator, if the device is iphone/ipad, the switch doesn't work in iphone. Could anyone tell me if it works in real iphone?

![image](https://cloud.githubusercontent.com/assets/3455798/16756811/21af8364-483a-11e6-8cbb-32a6bb38903f.png)

**Comment by abpetkov** [comment]
You can make sure that it works here: http://abpetkov.github.io/switchery/

I just checked it on iPhone 6 and it's behaving perfect.

Closing the issue, don't know what was wrong with the chrome dev tools. If you want to re-open this, make sure you provide more stable information about a bug.
