### ISSUE TITLE
How to do a simple jquery on click to show hide div based on if toggle on or off?

### ISSUE THREAD

**Issue by waynep16** [abpetkov/switchery#110]
As title says, prop checked isnt working so im trying just on click but that doesn't work because the checkbox changes to a span

`$('#toggleID').on('click', function (){
    $('dive').fadeToggle();
});`

doesn't work .... 

whats the easiest way?

**Comment by reefdog** [comment]
@waynep16 I can't see how this is Switchery related. Presumably, you're trying to bind a function to every time the checkbox changes from checked to unchecked (and vice versa)? You want the `change` event.

```javascript
$('#some_checkbox').on('change', function(){
  var checked = $(this).prop('checked');
  if (checked) {
    // Do thing you want to happen now that the checkbox is checked
  } else {
    // Do thing you want to happen now that the checkbox is not checked
  }
});
```
