### ISSUE TITLE
! Obsolete library, this can be done in plain css

### ISSUE THREAD

**Issue by DmitryGonchar** [abpetkov/switchery#114]
I see some people still try to use this library, however **the same thing can be done with plain css**. 
@abpetkov If possible, please mark library as obsolete or deprecated (similar to [this package](https://github.com/angular-ui/ui-select2) for example)

Demo: https://jsbin.com/redixohihu/1/edit?html,css,output

**The trick is to put `<input>` inside `<label>`**. Then by clicking anywhere in the label - you will have a change of state. Styles were taken from the switchery itself. Much _better than using > 1000 lines library_.

Pasting code here, in case the link becomes obsolete. 

```
<label>
    <input type="checkbox" class="ios-switch-cb">
    <span class="switchery"></span>
</label>
```

```
.ios-switch-cb {
  display: none;
}

.switchery {
  background-color: #fff;
  border: 1px solid rgb(223, 223, 223);
  border-radius: 20px;
  cursor: pointer;
  display: inline-block;
  height: 30px;
  position: relative;
  vertical-align: middle;
  width: 50px;
  -moz-user-select: none;
  -khtml-user-select: none;
  -webkit-user-select: none;
  -ms-user-select: none;
  user-select: none;
  box-sizing: content-box;
  background-clip: content-box;

  box-shadow: rgb(223, 223, 223) 0px 0px 0px 0px inset;
  transition: border 0.4s, box-shadow 0.4s;
}

.switchery:before {
  content: '';
  background: #fff;
  border-radius: 50%;
  box-shadow: 0 1px 3px rgba(0,0,0,0.4);
  position: absolute;
  top: 0;
  left: 0;
  height: 30px;
  width: 30px;
  transition: background-color 0.4s, left 0.2s;
}

.ios-switch-cb:checked + .switchery {
  background-color: rgb(100, 189, 99);
  box-shadow: rgb(100, 189, 99) 0px 0px 0px 16px inset;
  transition: border 0.4s, box-shadow 0.4s, background-color 1.2s;
  border-color: rgb(100, 189, 99);
}

.ios-switch-cb:checked + .switchery:before {
  left: 20px;
}
```

**Comment by shehi** [comment]
Oh man! Thanks for sharing this!

**Comment by jfvoliveira** [comment]
I've tested this but the "click" event won't change the checkbox. What am I doing wrong?

**Comment by abpetkov** [comment]
It can. That's part of the reason, I'm close to not maintaining this repo anymore, though I'm releasing fixes occasionally.

There's plenty of examples on the web and the world has changed a lot since I created this repo, when the CSS solution was not as stable cross-browser solution as I wanted it to. Therefore this came to live.

Thanks for sharing this, we've already been through that talk in other issues. I believe every sane developer out there knows what's the best solution for his project and how to adequately use it.

**Comment by DmitryGonchar** [comment]
@abpetkov Ok, although I have not found these issues by searching "obsolete" and "deprecated" words.

Could you then place this info to some visible place in the Readme.md file? Otherwise every sane developer does not have all the information he/she needs to make a decision. 

Also, let's not forget about middle and junior developers.

**Comment by shehi** [comment]
Middle and Junior developers should LEARN. Not waste someone else's 
money and time. :)
