### ISSUE TITLE
Switchery: make checkbox like a radio button

### ISSUE THREAD

**Issue by KingGeneral** [abpetkov/switchery#117]
i already make it look like a radio button with checkbox,
just a little bit of bug here, the switchery wont toggle, but the data is already checked there. 
(i already tried with several code but still like that, any idea ?? ),

https://jsfiddle.net/kinggeneral/g94gkaL7/

**Comment by abpetkov** [comment]
@KingGeneral It's not a bug. A Switchery element is not supposed to be a checkbox - see <a href="https://github.com/abpetkov/switchery/blob/master/switchery.js#L67">this part of the code</a>.

Here's an explanation in the past for that: https://github.com/abpetkov/switchery/issues/78

I believe you can make this functionality you have in there work with checkboxes as well though. Shouldn't be a lot more complex. Good luck!
