### ISSUE TITLE
Can not modify Switch State using jQuery event

### ISSUE THREAD

**Issue by uttamnestcode** [abpetkov/switchery#119]
i am trying to trigger Switch mode to off using jQuery but i am unable to find actual way to do so.
This is my initialise method:

```
var defaults = {
    color: "#052e65"
};
$('.init_switchery').each(function() {
    var $this = $(this),
        $options = $.extend({}, defaults, $this.data());
    new Switchery(this, $options);
});
```

I am trying to trigger Switch off using Click event on self. 

```
$('.init_switchery').on('click', function() {
    // Here i can see my switch is on after i click on it
    setTimeout(function() {
        // i want to trigger switch off after 5 seconds of clicking on it 
    }, 5000);
});
```

**Comment by abpetkov** [comment]
Check out the <a href="https://github.com/abpetkov/switchery#enable">enable</a> and <a href="https://github.com/abpetkov/switchery#disable>disable</a> methods. There are working examples in the <a href="http://abpetkov.github.io/switchery/">demo page</a> with source code.
