### ISSUE TITLE
set position of switch with multiples switches

### ISSUE THREAD

**Issue by maciejbuchert** [abpetkov/switchery#123]
Hello.
I have a lot of switches on site and I want to control position of each switches separately.
Each of swtiches have other ID and problem is that I can't use `$(element).click();` or `$(element).trigger('click');` because each switch runing a function. Aboves codes creating loop.

**Comment by notflip** [comment]
+1

**Comment by maciejbuchert** [comment]
@abpetkov Can you help ?

**Comment by jwwb681232** [comment]
虽然我不能解答你的问题，但是你却解决了我的问题。一直不知道全选怎么操作，但是看了你的`$(element).click();`得到了启发，谢谢
