### ISSUE TITLE
Can be done with pure CSS and less code

### ISSUE THREAD

**Issue by ProLoser** [abpetkov/switchery#13]
Here's a demo:

http://jsfiddle.net/ProLoser/bM4C9/

Doesn't require Javascript and should have excellent browser support. I tend to prefer declaring the colors in CSS instead of JS anyway.

**Comment by damianof** [comment]
@ProLoser are you going to create a repo with your css solution?

**Comment by ProLoser** [comment]
@damianof no because it's not something people should be including into their project as a 3rd party lib, just learn css. At best I would throw it on a tips and tricks collection

**Comment by damianof** [comment]
Maybe a repo of CSS snippets....

**Comment by bobbyg603** [comment]
> Here's a demo:
> 
> http://jsfiddle.net/ProLoser/bM4C9/
> 
> Doesn't require Javascript and should have excellent browser support. I tend to prefer declaring the colors in CSS instead of JS anyway.

Hey @ProLoser , do you have a copy of this CSS you might share? unfortunately this jsfiddle seems to have been lost in the river of time. Thank you!

**Comment by ProLoser** [comment]
@bobbyg603 Google "css switch"

https://freefrontend.com/css-toggle-switches/

**Comment by bobbyg603** [comment]
thanks @ProLoser i ended up finding one, here's the one i went with for anyone looking at this thread in the future https://codepen.io/TazTheManiac/pen/rGrpMg
