### ISSUE TITLE
I can`t click it  in jquery.steps / switchery 按钮点击没有反应

### ISSUE THREAD

**Issue by XLJ-CN** [abpetkov/switchery#142]
**************english  description*************
I can`t click it  in jquery.steps   and it can`t change
there are something wrong  that i can`t click it ！
 in my browser develop mode  
i see it can‘t bind a function --> click ;  in line 638
line 638 is 
  if (switcher.addEventListener) {
                    switcher.addEventListener("click",
                    function() {
                        self.setPosition(true);
                        self.handleOnchange(self.element.checked)
                    })   

 some switchery button  i can click it  in steps
so    how can i resolve it ？ anyone  ?
**********************中文描述*****************************
英文打的太累了
这样的
我在 jquery.steps 使用switchery 按钮    第一个steps 是OK的   但是  在第二个页面  搞死 没反应 能定义 能默认checked  但是点击就是没变化
我在火狐浏览器里面F12  看能点击的按钮 都绑定了一个click事件   在源码的638行
 if (switcher.addEventListener) {
                    switcher.addEventListener("click",
                    function() {
                        self.setPosition(true);
                        self.handleOnchange(self.element.checked)
                    })   
就是这个
但是  我在第二个steps里面定义的按钮   没有绑定上这个事件
 有大神遇到过吗    求破！

**Comment by XLJ-CN** [comment]
I init it by 
  $("[name='IS_SHARE_CYCLE']").each(function () {
                var tmp = new Switchery($(this)[0]);    
            });

**Comment by radu-singer** [comment]
I can confirm this problem . When adding a switchery checkbox inside 
```
<fieldset data-step="...">
   <div class="form-group"> 
```
where fielset is a step of a wizard implemented with http://www.jquery-steps.com , it can't be clicked

**Comment by XLJ-CN** [comment]
sorry sir
 I have solved it 
 I show init it again in the  steps
