### ISSUE TITLE
Problem with <label> elements

### ISSUE THREAD

**Issue by mgrn0** [abpetkov/switchery#15]
I tried to use switchery in a recent project and stumbled upon a problem when used with <label> elements:

```
<li><label>
    <input type="checkbox" value="foo" class="js-switch" checked="checked" />
labelname
</label>
</li>
```

I can click the checkbox once, but not a second or third time. it seems to me that the label somehow interferes with the checkbox, if I remove the label everything works smoothly (but labels are there for a reason ;)

Happens in Chrome and Firexox, same faulty behaviour.

is switchery intended to work with labels? It would be cool if a click on the correspondig label would trigger a checkbox switch, too.

Working example can be found here: http://dl.dropboxusercontent.com/u/81358/temp/switchery/index.html (first checkbox has a label, second has none).

**Comment by igorladela** [comment]
I use working version 0.6.1
