### ISSUE TITLE
Feature request: would love to have different sized switches.

### ISSUE THREAD

**Issue by faoiseamh** [abpetkov/switchery#24]
These switches are great, but they'd be even better with a small version to fit into smaller UI areas. I will build this if I have some more time down the road, but logging for now in case anyone else wants to sooner.

**Comment by alimovz** [comment]
.small + .switchery {
   height: 15px;
   width: 25px;
}

.small + .switchery > small {
   height: 15px;
   width: 15px;
}

That's pretty slick. Thanks tkh44.

**Comment by abpetkov** [comment]
@gsans @alimovz Predefined sizes are released since <a href="https://github.com/abpetkov/switchery/releases/tag/0.7.0">0.7.0</a>.
