### ISSUE TITLE
Changing a Switchery checkbox state from code

### ISSUE THREAD

**Issue by ghost** [abpetkov/switchery#25]
Not convenient approach for initialization and no why to pass state via setting nor via java-script. 

Please provide a way to change state from code

**Comment by JacerOmri** [comment]
@dafinley idea is the best so far...

**Comment by damiensawyer** [comment]
After playing around with all these, the best way I found was to just send it a click via Jquery. 
$(element).trigger('click');

**Comment by RomaricMollard** [comment]
I am agree with damiensawyer, I wrote a little function to setState an element
`function changeSwitcheryState(el,value){`
` if($(el).is(':checked')!=value){`
`		$(el).trigger("click")`
`	}`
`}`

**Comment by damiensawyer** [comment]
Cool. 

If anyone's interested, I implemented it as a knockout js binding as follows. This allows it to be bound to an observable boolean:

```
ko.bindingHandlers.switchery = {
    init: function (element, valueAccessor, allBindingsAccessor, viewModel, bindingContext) {
        var options = (allBindingsAccessor().options ||
            {
                size: 'small'
            });
        var v = valueAccessor();
        $(element).prop('checked', v());
        var e = new Switchery(element, options);
        element.onchange = function () {
            if (ko.isObservable(v)) {
                v(element.checked);
            }
        };
    },
    update: function (element, valueAccessor, allBindingsAccessor, viewModel, bindingContext) {
        var value = ko.unwrap(valueAccessor());
        var currentValue = element.checked;
        if (currentValue != value) {
            //e.setPosition(value); // didn't seem to work... so just send it a click.
            $(element).trigger('click');
        }
    }
};
//ko.virtualElements.allowedBindings['switchery'] = false;
```

**Comment by lfern** [comment]
Try to change checked property and then invoke setPosition()

**Comment by FrankenApps** [comment]
I have two checkboxes and I want the not clicked checkbox to change when I click one of them (essentially a radio group with two radio buttons). Now when I `.trigger('click')` it seems to somehow override the change of the clicked checkbox, so that only the not clicked changes its state. See this [JSFiddle](http://jsfiddle.net/61r6dcew/1/).

**Comment by PhilippeMarcMeyer** [comment]
For myself, I check if the checkbox is a different state than the one I want and then trigger a click
`var isChecked = $("#myCheckBox").is(':checked');`
` if (isChecked != data.IsActive) {`
`        $("#myCheckBox").parent().find(".switchery").trigger("click");`
` }`

**Comment by LuizFritsch** [comment]
I had this problem and I was calling an onclick function so I couldn't trigger any click event or It would start an infinite loop. I managed to solve like this:


`$("#" + registro).siblings('span').remove();`
`var sw = new Switchery($("#" + registro)[0]);`
`sw.setPosition(true);`
