### ISSUE TITLE
Handle input change event

### ISSUE THREAD

**Issue by shlima** [abpetkov/switchery#27]
Hello. Switchery does not handle the `onchange` input's event and auto-update self state. Why is that? Can we implement this feature?

**Comment by amitshahc** [comment]
> [Here's a preview](http://jsfiddle.net/3am89/).

This really worked. but should be provided with native kind of function in this lib.

**Comment by MohamedHana** [comment]
```
let input = document.querySelector('#input');
let switch = new Switchery(input);

$('#input').on('change', function(e) {
    console.log(switch.element.checked);
});
```

I tried this and it works fine.
