### ISSUE TITLE
Make a switchery enabled or disabled

### ISSUE THREAD

**Issue by iNetw0rker** [abpetkov/switchery#30]
Hello,
I am from Germany, so, sorry for my (possibly) bad english.
I've got two switchery check-boxes and one iput-field:
<input type="checkbox" class="js-switch js-check-change4" checked /> e-mail<br />
<input type="checkbox" class="js-switch js-check-change5" checked disabled/>Use alternate e-mail<br />
<input type="text" value="Alternate e-mail" id="altmail" disabled />

At the End of the page, I've got the following JS:
<script type="text/javascript">
var elems = Array.prototype.slice.call(document.querySelectorAll('.js-switch'));

elems.forEach(function(html) {
  var switchery = new Switchery(html, { color: '#41b7f1', secondaryColor: '#41b7f1' });
});

	  var changeCheckbox4 = document.querySelector('.js-check-change4');
	  var changeCheckbox5 = document.querySelector('.js-check-change5');
	  
	  changeCheckbox4.onchange = function() {
		  $("#altmail").attr('disabled', this.checked);
		  if(changeCheckbox5.disabled == true){
		  	  changeCheckbox5.disabled=false;
			  console.log("activate box");
		  }
		  else{
		  	  changeCheckbox5.disabled=true;
			  console.log("deactivate box");
		  }
      };
</script>
What I want is, that when "changeCheckbox4" is checked, then "changeCheckbox5" and the inputfield (#altmail) should be disabled and when "changeCheckbox4" is unchecked, "changeCheckbox5" and #altmail should be enabled.
My code works for the input-field (#altmail), but not for the switchery checkbox "changeCheckbox5". BUT the state of changeCheckbox5 seems to change, because the console in Google Chrome shows me alternating "enable box" and "disable box".
However, the changeCheckbox5 remains disabled...

I don't know what to do, hope you can help me.
iNetw0rker

Edit: How to show you my code?

**Comment by murtali** [comment]
+1

**Comment by corford** [comment]
Just wanted to add another +1. It would be great if we could enable/disable switchery on the fly after instantiation (e.g. in my case I use a switch to trigger an animation elsewhere on the page and want to wait for that to complete before letting users toggle the switch again).

**Comment by mehmetgunturkun** [comment]
+1

**Comment by mennooo** [comment]
+1

**Comment by jakeorr** [comment]
+1

**Comment by abpetkov** [comment]
Released in <a href="https://github.com/abpetkov/switchery/releases/tag/0.8.0">0.8.0</a>

**Comment by korcstar** [comment]
var elem = document.querySelector('.js-switch');
var switchery = new Switchery(elem);
switchery.disable();
switchery.enable();

it works with current version
Thanks

**Comment by learnsomethingin** [comment]
am still getting the error, the error is 'Uncaught TypeError: Cannot read property 'disabled' of null'
the line no. is 1905 in 'switchery.js'

Error:
Switchery.prototype.isDisabled = function() {
  return this.options.disabled || this.element.disabled || this.element.readOnly;  // this is the error line
};

**Comment by johnroodt** [comment]
Your English is just fine...I'm having the same problem with Switchery.

Switchery.prototype.isDisabled = function() {
return this.options.disabled || this.element.disabled || this.element.readOnly; // this is the error line
};

I see you've had no reply for 24 days...so I guess there's no pending fix for this?

**Comment by msopko81** [comment]
@learnsomethingin and @johnroodt 

The only time I got the error you mention, I forgot to remove the following code:

var switchery_proof_of_mailing = new Switchery(document.querySelector('.js-dynamic-state'));

I did not have any elements with the js-dynamic-state as the class. Try double checking when you are calling the Switchery function and making sure elements exists or that you have a proper if test beforehand.

**Comment by leon0707** [comment]
@korcstar Seems like disable and enable functions are not attached to the element. If I use $('....') to get the switchery element, I cannot run $('....').disable(); Any solutions?
