### ISSUE TITLE
switchery does not allow programmatic control of the position with javascript

### ISSUE THREAD

**Issue by spedemon** [abpetkov/switchery#40]
setting the state of the switch, e.g.: 
switch.checked = true; 
does not update the switch position on screen.

**Comment by rajukt** [comment]
Hi,
refer this Link
http://jsfiddle.net/radha9611/2op24yc5/1/

**Comment by pravidreamer** [comment]
@rajukt Thanks Raju :) This is exactly what I was looking for... Keep it up

**Comment by rajukt** [comment]
@pravidreamer WellCome :)
