### ISSUE TITLE
Double onchange event with bootstrap label

### ISSUE THREAD

**Issue by ottob** [abpetkov/switchery#50]
If I click the toggle I get two alert popups. When I click the label I only get one as expected. Example here http://jsfiddle.net/ar6jmjju/2/

It seems like another project had a similar issue: https://github.com/nostalgiaz/bootstrap-switch/issues/102

**Comment by jirkadev** [comment]
It's not always convenient to place the switcher outside of the `<label>`. I fixed this issue in my fork https://github.com/jirikrepl/switchery/commit/174cb248c7504f5b1e9bf1b87579b7861d2af212
