### ISSUE TITLE
Rails-assets package convertion issue

### ISSUE THREAD

**Issue by theycallmeS** [abpetkov/switchery#53]
Switchery bower packages gives the following error when trying to convert it for use with [rails-assets](http://rails-assets.org):
![2014-12-31 2 24 58](https://cloud.githubusercontent.com/assets/1417422/5584092/d34f21e2-9094-11e4-875c-df61dd2b51dd.png)

**Comment by abpetkov** [comment]
It should be ok now.

![rails_assets](https://cloud.githubusercontent.com/assets/1809512/5605453/c27ca0a6-9404-11e4-9de1-8ed1218b8609.png)
Let me know if it works for you as well.
