### ISSUE TITLE
Keep the Switchery object in element data

### ISSUE THREAD

**Issue by SpartakusMd** [abpetkov/switchery#55]
Something like:

```
var switchery = new Switchery(elem, { disabled: true });
jQuery(elem).data('switchery', switchery);
```

**Comment by Rikcon** [comment]
For someone who will face the same issue in future.
But my method is jquery dependent.
Create your switchery objects like this: 
```
      var elems = Array.prototype.slice.call(document.querySelectorAll('.switcher'));
        elems.forEach(function (html) {
            var switchery = new Switchery(html);
            $(html).data('ObjSwitchery', switchery);
        });
```
` $(html).data('ObjSwitchery', switchery);` is the main thing here, we're storing switchery object with the checkbox itself.

For example in change event you need this object ( to disable checkbox or smth).

```
var ObjSwitchery = $(element).data('ObjSwitchery');
ObjSwitchery.disable();
```
