### ISSUE TITLE
Align switchery inside a table cell

### ISSUE THREAD

**Issue by tggm** [abpetkov/switchery#56]
Is there away to center horizontally the switch inside a <TD> ? 

The switch remains left-aligned.

**Comment by abpetkov** [comment]
Inside a? A what? Inside a div or some other container/wrapper I guess? <a href="http://jsfiddle.net/hyymaeek/">Here</a> is a solution for you if that's the case.

Remember this is most probably an issue with your implementation, which is not related to the library. I'm just feeling cool enough today to solve people's problems. :sunglasses:

**Comment by abpetkov** [comment]
Inside a? A what? Inside a div or some other container/wrapper I guess? <a href="http://jsfiddle.net/hyymaeek/1">Here</a> is a solution for you if that's the case. Please confirm if it's all good.

Remember this is most probably an issue with your implementation, which is not related to the library itself. I'm just feeling cool enough today to solve people's problems. :sunglasses:
