### ISSUE TITLE
Animating disabled state

### ISSUE THREAD

**Issue by Bartzy** [abpetkov/switchery#57]
Hi,

Is it possible to animate the disabled state (going in and out of this state) ?

Thanks!

**Comment by abpetkov** [comment]
In general, you'll find difficulties changing disabled state dynamically (<a href="https://github.com/abpetkov/switchery/issues/30">issue #30</a>) therefore you'll have the same difficulties when trying to animate it. I'm not exactly sure what is it that you want to do, so if you could give some more details, I'll try to help.

**Comment by Bartzy** [comment]
Thanks for the answer,
By animating I meant fading in the color change when disabling and enabling a switch.

**Comment by abpetkov** [comment]
You can extend the plugin's styles, by adding CSS3 transition to the opacity property (we lower opacity on disabled switches). That might easily work, but in any case this is something you should build on your side.

**Comment by justein** [comment]
I want to know how to change to swtiches's disabled state dynamically..

**Comment by abpetkov** [comment]
Check the issue, I've linked above. It's addressing the same thing.
