### ISSUE TITLE
ng-true-value and ng-false-value not working

### ISSUE THREAD

**Issue by daw451-duplicate** [abpetkov/switchery#59]
So the ng-true-value="0 and ng-false-value="1" partly work.... when the page initializes and presents the switch it does not show the correct value. So for instance, if the value from the ajax call is an integer value of 0 the control is checked false and the value is set to -1. BUT once I start clicking the control it begins to work properly. As I check the switch it changes the underlining model to 0 and false it changes it to 1.

Any ideas to get the initialization of the switch and model in sync at start up?

aaron

**Comment by abpetkov** [comment]
I assume you're using the Angular directive?

**Comment by abpetkov** [comment]
I'm guessing yes. In any case, I'm not the maintainer of it, so it would be more suitable to ask in the <a href="https://github.com/servergrove/NgSwitchery">Angular repo</a>
