### ISSUE TITLE
RequireJS loading broken

### ISSUE THREAD

**Issue by Zagitta** [abpetkov/switchery#64]
Greetings, I'm getting a 'TypeError: object is not a function', exception at switchery.js:1832 require.register.Switchery.handleClick. It seems that loading Switchery with RequireJS breaks click events due to Fastclick not being defined properly or something along those lines.

Here's a jsfiddle demonstrating the issue: https://jsfiddle.net/bpy8qu9q/

Am I doing something wrong or is this a bug?
Thank you for the great library and thanks for the help in advance.

Best regards, Zagitta

**Comment by abpetkov** [comment]
Thanks for the feedback. This issue was reported a while ago - https://github.com/abpetkov/switchery/issues/22. Unfortunately, I still haven't found the time to work on this, so this is still unresolved. There's a temporary solution you can use, until I make that work right. Cheers.
