### ISSUE TITLE
Meteor package

### ISSUE THREAD

**Issue by jiku** [abpetkov/switchery#67]
Can't seem to make it work in Meteor, by [itself](http://meteorpad.com/pad/mafjHk77GfzH7G38Z/Switchery) or by including any of the widely used Bootstrap packages

[bootstrap](http://meteorpad.com/pad/wwkW9XSZqK5YJNL72/Switchery%20with%20bootstrap)

[mizzao:bootstrap-3](http://meteorpad.com/pad/GrMLtrxaiackfgLeB/Switchery%20with%20mizzao:bootstrap-3)

[twbs:bootstrap](http://meteorpad.com/pad/aP9ALAfuxSuxxYDn4/Switchery%20with%20twbs:bootstrap)

Maybe it's a load order issue, but I can't get it to work locally either. No console errors that I can see, either on Meteorpad or when going to the instance URLs. (Using latest Chrome.)

**Comment by abpetkov** [comment]
I managed to run it locally by itself. Here is what I did:
- Set up a simple app with `meteor create <app-name>`.

- In my main HTML file I added:
```html
<body>
  {{> switchery}}
</body>

<template name="switchery">
  <input type="checkbox" class="js-switch" checked />
</template>
```

- In my main JS file I added:

```js
if (Meteor.isClient) {
  Template.switchery.rendered = function() {
    var elem = this.find('.js-switch');
    var init = new Switchery(elem);
  };
}
```

And that was enough. I'm assuming you have something wrong with your code in this case. Still, I'd better have @mediatainment have a word on this, as he was the one that initiated the creation of the Switchery Meteor package (<a href="https://github.com/abpetkov/switchery/pull/54">PR #54</a>) and I'm not an expert when it comes to Meteor.

**Comment by jiku** [comment]
Thanks! Then it was just a matter of not using templates it seems. With onRendered it's working [here](http://meteorpad.com/pad/NPS8CNHt8ZgdzE2LL/Switchery%20(Working)) with events, etc.

/client/app.js
```
Template.switchery.onRendered(function () {
  var elem = this.find('.js-switch');
  var init = new Switchery(elem);
});

Template.switchery.events({
  "change .js-switch": function (event) {
    console.log("Works");
  }
});
```
