### ISSUE TITLE
How do you change switch option from JavaScript

### ISSUE THREAD

**Issue by respectYourNeighbour** [abpetkov/switchery#71]
I cannot change the state of the checkbox from JavaScript code, the following code doesn't work, I cannot see the switch button animate the change.

$("#myCheck").on('click', function() {
	document.getElementById("inlineCheckbox").checked = true;
});

**Comment by abpetkov** [comment]
https://github.com/abpetkov/switchery/issues/70

**Comment by respectYourNeighbour** [comment]
This was the fastest response I got on github!
You guys rull! +1:

**Comment by Sanafan** [comment]
How did you select your switchery element now? I can not get them by the id from the outside div. So how do i select a spefic switch via JavaScript and can tell her .enable(); ?

**Comment by abpetkov** [comment]
@Sanafan adressed your question in https://github.com/abpetkov/switchery/issues/70
