### ISSUE TITLE
If disabled cannot be re-enabled

### ISSUE THREAD

**Issue by dpierangeli** [abpetkov/switchery#73]
In this function the if conditions are not met when the switch are enabled.

Switchery.prototype.disable = function() {
  if (this.options.disabled) this.options.disabled = true;
  if (this.element.disabled) this.element.disabled = true;
  if (this.element.readOnly) this.element.readOnly = true;
  this.switcher.style.opacity = this.options.disabledOpacity;
  this.destroy();
};

In that case if we have an external code as
if isDisabled() 
 disable()
if !isDisabled()
  enable()

When disabled is not possibile to re-enable the switch.

I think that the code should be:

Switchery.prototype.disable = function() {
  if (!this.options.disabled) this.options.disabled = true;
  if (!this.element.disabled) this.element.disabled = true;
  if (!this.element.readOnly) this.element.readOnly = true;
  this.switcher.style.opacity = this.options.disabledOpacity;
  this.destroy();
};

**Comment by dpierangeli** [comment]
Sorry to bother, i have done the modification myself but i'm learning to use git so i prefer non to create a pull request to not create mess (also sorry for the bad english)

**Comment by abpetkov** [comment]
Fixed in https://github.com/abpetkov/switchery/releases/tag/0.8.1. Cheers.
