### ISSUE TITLE
Does Switchery work on Radio Buttons

### ISSUE THREAD

**Issue by jhyland87** [abpetkov/switchery#78]
Can I get switchery to work on Radio Buttons? I wanted the checkboxes and radio buttons to look similar, so can I use it for both?

Thanks

**Comment by abpetkov** [comment]
The idea behind the switch toggle is to provide a simple yes/no option to the user. Therefore I'm only allowing a checkbox input type to work, as it's native functionality covers that idea entirely. The radio buttons have a totally different purpose and that is the reason I'm not planning to support radio buttons at all.
