### ISSUE TITLE
Make Switch Check Uncheck by code

### ISSUE THREAD

**Issue by mohsinbalocch786** [abpetkov/switchery#84]
i don't find any method to make switch check/ uncheck by code,
so i write my own in code
in switchery.js
 Switchery.prototype.makeChecked = function() {
        	var checked = this.isChecked(),
            switcher = this.switcher,
            jack = this.jack;
        	this.element.checked = true;
            if (window.getComputedStyle) jack.style.left = parseInt(window.getComputedStyle(switcher).width) - parseInt(window.getComputedStyle(jack).width) + "px";
            else jack.style.left = parseInt(switcher.currentStyle["width"]) - parseInt(jack.currentStyle["width"]) + "px";
            if (this.options.color) this.colorize();
            this.setSpeed()
        };
        Switchery.prototype.makeUnchecked = function() {
        	var checked = this.isChecked(),
            switcher = this.switcher,
            jack = this.jack;
        	jack.style.left = 0;
            this.element.checked = false;
            this.switcher.style.boxShadow = "inset 0 0 0 0 " + this.options.secondaryColor;
            this.switcher.style.borderColor = this.options.secondaryColor;
            this.switcher.style.backgroundColor = this.options.secondaryColor !== defaults.secondaryColor ? this.options.secondaryColor : "#fff";
            this.setSpeed()
        };

and Use those methods as 
var elems = Array.prototype.slice.call(document.querySelectorAll('.js-switch132'));
	var switchery=[];
	elems.forEach(function(html) {
	
		switchery[html.getAttribute('id')] = new Switchery(html,{ size: 'large' });
	})
	function toggleSwitchery(id)
	{
	    var s = switchery[id];
	    s.makeChecked();
	}
       function makeUnchecked(id)
	{
	    var s = switchery[id];
	    s.makeUnchecked();
	}

**Comment by rajukt** [comment]
Hi, 
Check this link
http://jsfiddle.net/radha9611/2op24yc5/1/
In this OnCheck of Main Switchery Child Switchery is Changing

**Comment by VelizarHristov** [comment]
This is what I use for toggle:

`telnetSwitch.setPosition(true);`

But it took me a bit of work to find it and I'm still not sure how to set state to on / off. Would be nice if it is added to the demo page.

**Comment by abpetkov** [comment]
You will find good examples of how to deal with that, without manipulating the code in the package, in issue https://github.com/abpetkov/switchery/issues/27 and the issues referenced in there.

**Comment by jogi-skills** [comment]
Thanks brother....!! @mohsinbalocch786
