### ISSUE TITLE
Check all/Select all functionality in Switchery

### ISSUE THREAD

**Issue by pravidreamer** [abpetkov/switchery#87]
How to achieve Check all/Select all functionality in Switchery? The event is not firing... somebody please help!

**Comment by rajukt** [comment]
Hi Praveen,

refer this Link
http://jsfiddle.net/radha9611/2op24yc5/1/

**Comment by abpetkov** [comment]
There are plenty of closed issues on selecting/deselecting the switches. It's pretty much the same, but you run a loop with all checkbox elements inside. Here's a good starting point for your research: https://github.com/abpetkov/switchery/issues/84

**Comment by pravidreamer** [comment]
@rajukt Thanks Raju... @abpetkov I got it... Thanks a lot :)
