### ISSUE TITLE
change state with simple code

### ISSUE THREAD

**Issue by kristdev** [abpetkov/switchery#92]
Hello, i would like to control the state from code.
 `$('.lundi').prop('checked', true);`
does not work.

How can i do?

**Comment by svetlinyotov** [comment]
Just run on the same issue.
Check the second answer [here](http://stackoverflow.com/questions/21931133/changing-a-switchery-checkbox-state-from-code) by Tom Gerken
I found it working for me.
Hope it helps :+1:

**Comment by abpetkov** [comment]
How to handle change checkbox state dynamically: https://github.com/abpetkov/switchery/issues/27

**Comment by maciejbuchert** [comment]
Sorry for reopen, but I don't want create new issue.
@svetlinyotov How can I do this with multiple switches ?
