### ISSUE TITLE
using switchery with dynamically created checkboxes

### ISSUE THREAD

**Issue by minieggs** [abpetkov/switchery#95]
I'm new to GiT hub and I've just posted this on an old thread as it was similar but it looks like that thread has been closed so I'm posting again here

I think I have a similar issue.

I have downloaded your switchery.css/js and have them working fine in a standalone webpage

I'm no JS expert and I'm now trying to use them in a proprietary framework

I notice that the js file is included at the end of the html file.

I assume this is because the checkbox elements need to exist before the script executes ?

The framework I'm trying to use it in creates everything dynamically and i'm getting an error on line 1905 of switchery.js

Switchery.prototype.isDisabled = function() { return this.options.disabled || this.element.disabled || this.element.readOnly; };

Basically it is saying element is null and therefore it can't get the disabled property

Can you give me some simple clues on how i might use your switchery styling with my dynamically created checkboxes

Thanks

**Comment by abpetkov** [comment]
Make sure you create the Switchery instance after your element has been added dynamically. A lot of example on the web of how to do that.

This issue is not related to the package itself, so I'm closing it. Good luck!
