### ISSUE TITLE
Missing final ;

### ISSUE THREAD

**Issue by carlos-granados** [abpetkov/switchery#98]
The code generated in the dist dir is missing the final ; in the non minified version. Instead of 

```
} else {
  (this || window)["Switchery"] = require("switchery");
}
})()
```

it should be

```
} else {
  (this || window)["Switchery"] = require("switchery");
}
})();
```

This can cause problems if concatenating this library to other js libraries

**Comment by abpetkov** [comment]
Fixed in `0.8.2`.
